# Generated by Django 3.2.8 on 2021-10-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_master',
            new_name='user',
        ),
    ]
