# Generated by Django 3.2.8 on 2021-10-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='uri',
            field=models.CharField(default='', max_length=100),
        ),
    ]
