# Generated by Django 3.2.8 on 2021-10-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_track_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spotify_token',
            field=models.CharField(max_length=200),
        ),
    ]
