# Generated by Django 3.2.8 on 2022-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='refresh_token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
